image: node:lts-alpine3.9

stages:
  - fetch-version
  - build
  - release

fetch-version:
  stage: fetch-version
  artifacts:
    paths:
    - version
  script:
    - apk add --no-cache git
    - npm install @semantic-release/exec
                  @semantic-release/changelog
                  @semantic-release/gitlab
                  @semantic-release/git
    - npx semantic-release --dry-run
    - echo "New version -> $(cat version)"

build:
  stage: build
  artifacts:
    paths:
    - version
  script:
    - echo "Version -> $(cat version)"

release:
  stage: release
  script:
    - apk add --no-cache git
    - npm install @semantic-release/exec
                  @semantic-release/changelog
                  @semantic-release/gitlab
                  @semantic-release/git
    - npx semantic-release
